---
development:
  cloud_name: davebarthly
  api_key: '837836422587854'
  api_secret: H-BUxAN-NURYpNJBhMF7HFFGA-o
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: davebarthly
  api_key: '837836422587854'
  api_secret: H-BUxAN-NURYpNJBhMF7HFFGA-o
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: davebarthly
  api_key: '837836422587854'
  api_secret: H-BUxAN-NURYpNJBhMF7HFFGA-o
  enhance_image_tag: true
  static_image_support: false
