---
development:
  cloud_name: ds1rn0ryl
  api_key: '791142175615658'
  api_secret: K_t0_BsWMluePmiT5G7Y760_ldc
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: ds1rn0ryl
  api_key: '791142175615658'
  api_secret: K_t0_BsWMluePmiT5G7Y760_ldc
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: ds1rn0ryl
  api_key: '791142175615658'
  api_secret: K_t0_BsWMluePmiT5G7Y760_ldc
  enhance_image_tag: true
  static_image_support: false
